name: mobile_flutter
description: "CareConnect Mobile Flutter Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  pin_code_fields: ^8.0.1
  fl_chart: ^0.68.0
  table_calendar: ^3.1.2
  flutter:
    sdk: flutter

  # ---------------------------
  # State Management & Routing
  # ---------------------------
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0

  # ---------------------------
  # Persistence & Utilities
  # ---------------------------
  shared_preferences: ^2.2.3
  intl: ^0.19.0

  # ---------------------------
  # UI / Icons
  # ---------------------------
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Code Quality
  flutter_lints: ^6.0.0

  # Testing Utilities (important for Part 2)
  mocktail: ^1.0.4
  riverpod_test: ^0.1.6

flutter:
  uses-material-design: true

  # Assets (add later when you import images/icons)
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Fonts (add later if you import custom fonts from Figma)
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
